apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicontagem-deployment
  labels:
    app: apicontagem
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apicontagem
  template:
    metadata:
      labels:
        app: apicontagem
    spec:
      containers:
      - name: apicontagem
        image: azurenapratica/apicontagem:latest
        env:
          - name: TesteAmbiente
            valueFrom:
                secretKeyRef:
                  name: teste-groffe
                  key: VlTesteAmbiente
        ports:
        - containerPort: 80